### ISSUE TITLE
Load_net =load_net[param_key]         KeyError:'params'

### ISSUE THREAD

**Issue by wgfrhebnr** [csjliang/DASR#21]
Traceback (most recent call last):
  File "dasr/train.py", line 11, in <module>
    train_pipeline(root_path)
  File "/home/chenz/DASR/basicsr/train.py", line 128, in train_pipeline
    model = build_model(opt)
  File "/home/chenz/DASR/basicsr/models/__init__.py", line 27, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/home/chenz/DASR/dasr/models/DASR_model.py", line 20, in __init__
    super(DASRModel, self).__init__(opt)
  File "/home/chenz/DASR/basicsr/models/srgan_dynamic_model.py", line 41, in __init__
    self.load_network_init_alldynamic(self.net_g, load_path, self.opt['num_networks'], self.opt['path'].get('strict_load_g', True), load_key)
  File "/home/chenz/DASR/basicsr/models/base_model.py", line 377, in load_network_init_alldynamic
    load_net = load_net[param_key]
KeyError: 'params'

请问怎么解决这个问题？（How to address this problem?）

**Comment by zhangyifanaaa** [comment]
请问您这个问题解决了，我也遇到了这个问题

**Comment by liuyifan6613** [comment]
Add "params" in the test yml.
